apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reductrai.fullname" . }}-proxy
  labels:
    app.kubernetes.io/name: {{ include "reductrai.name" . }}-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: proxy
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "reductrai.name" . }}-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    {{- $services := (include "reductrai.services" .) | fromJson }}
    {{- $proxyShared := index $services.services "proxy" | default dict }}
    {{- $proxyEnv := $proxyShared.environment | default dict }}
    {{- $skipEnv := dict "REDUCTRAI_LICENSE_KEY" true "DATADOG_API_KEY" true "NEW_RELIC_API_KEY" true }}
    {{- $envOverrides := dict }}
    {{- range $k, $v := .Values.proxy.env }}
    {{- $_ := set $envOverrides $k (printf "%v" $v) }}
    {{- end }}
    {{- $_ := set $envOverrides "REDUCTRAI_COMPRESSION" (printf "%t" .Values.proxy.compression.enabled) }}
    {{- $_ := set $envOverrides "REDUCTRAI_COMPRESSION_LEVEL" .Values.proxy.compression.level }}
    {{- if .Values.backends.datadog.enabled }}
    {{- $_ := set $envOverrides "DATADOG_ENDPOINT" .Values.backends.datadog.endpoint }}
    {{- end }}
    {{- if .Values.backends.newrelic.enabled }}
    {{- $_ := set $envOverrides "NEW_RELIC_ENDPOINT" .Values.backends.newrelic.endpoint }}
    {{- end }}
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reductrai.name" . }}-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: proxy
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: proxy
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: REDUCTRAI_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "reductrai.fullname" . }}-license
                  key: license-key
            {{- if .Values.backends.datadog.enabled }}
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "reductrai.fullname" . }}-backends
                  key: datadog-api-key
            {{- end }}
            {{- if .Values.backends.newrelic.enabled }}
            - name: NEW_RELIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "reductrai.fullname" . }}-backends
                  key: newrelic-api-key
            {{- end }}
            {{- range $name, $cfg := $proxyEnv }}
            {{- if not (hasKey $skipEnv $name) }}
            {{- $override := index $envOverrides $name | default "" }}
            {{- $value := default $cfg.default $override }}
            {{- if $value }}
            - name: {{ $name }}
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          {{- if .Values.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "reductrai.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
