apiVersion: v1
kind: Service
metadata:
  name: {{ include "reductrai.fullname" . }}-proxy
  labels:
    {{- include "reductrai.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.proxy.service.type }}
  {{- if and (eq .Values.proxy.service.type "LoadBalancer") .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.proxy.service.type "NodePort") .Values.proxy.service.nodePort }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "reductrai.name" . }}-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
