{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reductrai.fullname" . }}-ollama
  labels:
    {{- include "reductrai.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "reductrai.name" . }}-ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 11434
      targetPort: 11434
      protocol: TCP
{{- end }}
